build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  apt_packages:
    - pandoc

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt